# Generated by Django 3.0.2 on 2020-01-12 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0003_auto_20200112_1245'),
    ]

    # operations = [
    #     migrations.RenameField(
    #         model_name='task',
    #         old_name='user1',
    #         new_name='author',
    #     ),
    # ]
