# Generated by Django 3.0.2 on 2020-01-12 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0005_auto_20200112_1520'),
    ]

    # operations = [
    #     migrations.RemoveField(
    #         model_name='task',
    #         name='user1',
    #     ),
    # ]
