# Generated by Django 3.0.2 on 2020-01-13 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0002_auto_20200109_1406'),
        ('apptasks', '0007_auto_20200113_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='author_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='appaccounts.Profile'),
        ),
    ]
