# # Generated by Django 3.0.2 on 2020-01-14 06:29

# import django.contrib.postgres.fields
# from django.db import migrations, models


# class Migration(migrations.Migration):

#     dependencies = [
#         ('apptasks', '0009_task_chekpoints'),
#     ]

#     operations = [
#         migrations.AlterField(
#             model_name='task',
#             name='chekpoints',
#             field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, default=list, null=True, size=None),
#         ),
#     ]

# Generated by Django 3.0.2 on 2020-01-14 06:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0009_task_chekpoints'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='chekpoints',
        ),
    ]
