# Generated by Django 3.0.2 on 2020-01-14 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0011_auto_20200114_0946'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='chekpoints',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='chekpoints', max_length=50),
        ),
    ]
