# Generated by Django 3.0.2 on 2020-01-14 07:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0013_remove_task_chekpoints'),
    ]

    # operations = [
    #     migrations.AddField(
    #         model_name='checkpointitem',
    #         name='id',
    #         field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
    #         preserve_default=False,
    #     ),
    #     migrations.AlterField(
    #         model_name='checkpointitem',
    #         name='checkpoint',
    #         field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='apptasks.CheckPoint'),
    #     ),
    # ]
