# Generated by Django 3.0.2 on 2020-01-21 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0015_auto_20200114_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='skill',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='apptasks/images/skills/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description',
            field=models.TextField(blank=True, default='', null=True, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='skill',
            name='description_min',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание'),
        ),
    ]
