# Generated by Django 3.0.2 on 2020-01-22 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0017_taskratings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='taskratings',
            name='created',
        ),
        migrations.AddField(
            model_name='taskratings',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
