# Generated by Django 3.0.2 on 2020-02-01 14:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appaccounts', '0003_profile_created'),
        ('apptasks', '0020_tasklike'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='description_HTML',
            field=models.TextField(default='', verbose_name='Форматированное описание'),
        ),
        migrations.AddField(
            model_name='task',
            name='description_short',
            field=models.CharField(default='', max_length=100, verbose_name='Краткое описание'),
        ),
        migrations.AlterField(
            model_name='task',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='task',
            name='author_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile', to='appaccounts.Profile'),
        ),
    ]
