# Generated by Django 3.0.2 on 2020-02-05 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0021_auto_20200201_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkpoint',
            name='order',
            field=models.IntegerField(blank=True, default=1, null=True, verbose_name='Порядок'),
        ),
        migrations.AlterField(
            model_name='task',
            name='title',
            field=models.CharField(max_length=150, verbose_name='Название задачи'),
        ),
    ]
