# Generated by Django 3.0.2 on 2020-02-08 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0022_auto_20200205_0914'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='cloud_url',
            field=models.URLField(blank=True, null=True, verbose_name='Cloud url'),
        ),
        migrations.AddField(
            model_name='task',
            name='github_pages_url',
            field=models.URLField(blank=True, null=True, verbose_name='Github pages'),
        ),
        migrations.AddField(
            model_name='task',
            name='github_repo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Github репозиторий'),
        ),
        migrations.AddField(
            model_name='task',
            name='heroku_url',
            field=models.URLField(blank=True, null=True, verbose_name='Heroku url'),
        ),
    ]
