# Generated by Django 3.0.2 on 2020-02-08 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0023_auto_20200208_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='build_storage',
            field=models.CharField(blank=True, choices=[(1, 'None'), (2, 'Github'), (3, 'Heroku')], default=1, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='task',
            name='code_storage',
            field=models.CharField(blank=True, choices=[(1, 'Github'), (2, 'Cloud')], default=1, max_length=50, null=True),
        ),
    ]
