# Generated by Django 3.0.2 on 2020-02-18 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0027_auto_20200218_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskfavourites',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_favourites', related_query_name='task_favourites', to='apptasks.Task'),
        ),
    ]
