# Generated by Django 3.0.2 on 2020-02-18 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0028_auto_20200218_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasklike',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_like', to='apptasks.Task'),
        ),
    ]
