# Generated by Django 3.0.2 on 2020-02-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0029_auto_20200218_1834'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='author_profile',
        ),
    ]
