# Generated by Django 3.0.2 on 2020-02-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0030_remove_task_author_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taskratings',
            name='task',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_rating', to='apptasks.Task'),
        ),
    ]
