# Generated by Django 3.0.3 on 2020-02-29 14:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0032_auto_20200229_1715'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='extra_skill1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_skill1', to='apptasks.Skill'),
        ),
        migrations.AddField(
            model_name='task',
            name='extra_skill2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_skill2', to='apptasks.Skill'),
        ),
        migrations.AddField(
            model_name='task',
            name='extra_skill3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='extra_skill3', to='apptasks.Skill'),
        ),
    ]
