# Generated by Django 3.0.3 on 2020-03-01 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0033_auto_20200229_1728'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='code_storage',
            field=models.CharField(blank=True, choices=[('1', 'Github'), ('2', 'Cloud'), ('3', 'Comment')], default='1', max_length=50, null=True),
        ),
    ]
