# Generated by Django 3.0.3 on 2020-03-06 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0003_auto_20200305_1644'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='description',
            field=models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание'),
        ),
    ]
