# Generated by Django 3.0.3 on 2020-03-06 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0004_subject_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='appcourses/images/courses/', verbose_name='Аватар'),
        ),
        migrations.AddField(
            model_name='subject',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='appcourses/images/subjects/', verbose_name='Аватар'),
        ),
    ]
