# Generated by Django 3.0.3 on 2020-04-08 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0006_auto_20200408_0751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='students',
        ),
    ]
