# Generated by Django 3.0.3 on 2020-04-08 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('appcourses', '0009_courseskillitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseskillitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('course',)}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
