# Generated by Django 3.0.3 on 2020-04-08 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0010_auto_20200408_1008'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='level',
            field=models.CharField(blank=True, choices=[('b', 'Beginner'), ('m', 'Middle'), ('a', 'Advanced'), ('p', 'Pro')], default='b', max_length=1, null=True),
        ),
    ]
