# Generated by Django 3.0.3 on 2020-04-08 17:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0014_auto_20200408_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='module',
            name='slug',
        ),
    ]
