# Generated by Django 3.0.3 on 2020-04-09 05:25

import appcourses.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0017_auto_20200408_2017'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название лекции')),
                ('description', models.CharField(max_length=200, verbose_name='Описание лекции')),
                ('order', appcourses.fields.OrderField(blank=True)),
                ('slug', models.SlugField(default='', max_length=210, unique=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='appcourses.Module')),
            ],
            options={
                'verbose_name': 'Урок',
                'verbose_name_plural': 'Уроки',
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='content',
            name='lesson',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='appcourses.Lesson'),
        ),
    ]
