# Generated by Django 3.0.3 on 2020-04-09 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0020_auto_20200409_0838'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='module',
        ),
    ]
