# Generated by Django 3.0.3 on 2020-04-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0021_remove_content_module'),
    ]

    operations = [
        migrations.AddField(
            model_name='text',
            name='description_HTML',
            field=models.TextField(default='', verbose_name='Форматированное описание'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.CharField(max_length=200, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='title',
            field=models.CharField(max_length=200, verbose_name='Название урока'),
        ),
    ]
