# Generated by Django 3.0.3 on 2020-04-11 13:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcourses', '0026_auto_20200410_2219'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(max_length=210, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=250, null=True, verbose_name='Краткое описание')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='appcourses/images/language/', verbose_name='Аватар')),
            ],
            options={
                'verbose_name': 'Язык программирования',
                'verbose_name_plural': 'Языки программирования',
                'ordering': ['title'],
            },
        ),
        migrations.AlterField(
            model_name='course',
            name='subject',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='courses', to='appcourses.Subject'),
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Название теста')),
                ('description', models.CharField(max_length=200, verbose_name='Описание теста')),
                ('slug', models.SlugField(default='', max_length=210, unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('type', models.CharField(choices=[('c', 'Common'), ('e', 'Exam')], default='c', max_length=1, null=True, verbose_name='Тип')),
                ('language', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='appcourses.Language')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to=settings.AUTH_USER_MODEL)),
                ('subject', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='appcourses.Subject')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'ordering': ['-created'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, null=True, verbose_name='Текст вопроса')),
                ('description', models.TextField(max_length=1000, null=True, verbose_name='Примечание')),
                ('type', models.CharField(choices=[('s', 'Single'), ('m', 'Multiple'), ('c', 'Code')], default='s', max_length=1, null=True, verbose_name='Тип')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('answer', models.TextField(max_length=1000, null=True, verbose_name='Правильный ответ (строка JSON)')),
                ('variants', models.TextField(max_length=1000, null=True, verbose_name='Варианты ответ (строка JSON)')),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to=settings.AUTH_USER_MODEL)),
                ('quiz', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='appcourses.Quiz')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['-created'],
            },
        ),
        migrations.AddField(
            model_name='course',
            name='language',
            field=models.ManyToManyField(null=True, related_name='courses', to='appcourses.Language'),
        ),
    ]
