# Generated by Django 3.0.3 on 2020-04-11 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0030_auto_20200411_1926'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы'),
        ),
    ]
