# Generated by Django 3.0.3 on 2020-04-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0031_question_score'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активен'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активен'),
        ),
    ]
