# Generated by Django 3.0.3 on 2020-04-11 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0033_auto_20200411_2057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='answer',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Правильный ответ (строка JSON)'),
        ),
        migrations.AlterField(
            model_name='question',
            name='description',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Примечание'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variants',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Варианты ответа (строка JSON)'),
        ),
    ]
