# Generated by Django 3.0.3 on 2020-04-12 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0034_auto_20200411_2103'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'ordering': ['order'], 'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AddField(
            model_name='question',
            name='text',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Текст вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(max_length=200, null=True, verbose_name='Название вопроса'),
        ),
    ]
