# Generated by Django 3.0.3 on 2020-04-12 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0035_auto_20200412_1057'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название вопроса'),
        ),
    ]
