# Generated by Django 3.0.3 on 2020-04-12 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0036_auto_20200412_1129'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='appcourses/images/quiz/avatars', verbose_name='Аватар'),
        ),
    ]
