# Generated by Django 3.0.3 on 2020-04-13 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0039_course_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='slug',
            field=models.SlugField(max_length=210, null=True, unique=True),
        ),
    ]
