# Generated by Django 3.0.3 on 2020-04-14 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0043_auto_20200414_1320'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активен'),
        ),
    ]
