# Generated by Django 3.0.3 on 2020-04-14 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0044_module_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='Описание урока'),
        ),
        migrations.AlterField(
            model_name='module',
            name='description',
            field=models.TextField(blank=True, max_length=1000, verbose_name='Описание модуля'),
        ),
    ]
