# Generated by Django 3.0.3 on 2020-04-15 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0046_auto_20200414_2158'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='active',
        ),
        migrations.RemoveField(
            model_name='image',
            name='active',
        ),
        migrations.RemoveField(
            model_name='text',
            name='active',
        ),
        migrations.RemoveField(
            model_name='video',
            name='active',
        ),
        migrations.AddField(
            model_name='content',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активен'),
        ),
    ]
