# Generated by Django 3.0.3 on 2020-04-20 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0049_auto_20200420_1303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=210, null=True, unique=True),
        ),
    ]
