# Generated by Django 3.0.3 on 2020-04-20 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0051_auto_20200420_1611'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='answer',
        ),
        migrations.AddField(
            model_name='question',
            name='code',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Код к вопросу (строка JSON)'),
        ),
        migrations.AddField(
            model_name='question',
            name='expected_result',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Ожидаемый результат (строка JSON)'),
        ),
    ]
