# Generated by Django 3.0.3 on 2020-04-21 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0054_auto_20200421_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Полное описание теста'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='overview',
            field=models.CharField(default='', max_length=200, verbose_name='Краткое описание теста'),
        ),
    ]
