# Generated by Django 3.0.3 on 2020-04-21 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0055_auto_20200421_1859'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='level',
            field=models.CharField(choices=[('b', 'Beginner'), ('m', 'Middle'), ('a', 'Advanced'), ('p', 'Pro')], default='b', max_length=1, null=True, verbose_name='Уровень'),
        ),
    ]
