# Generated by Django 3.0.3 on 2020-04-22 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('appcourses', '0056_quiz_level'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizResult',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('c', 'Completed'), ('p', 'In progress')], default='c', max_length=1, null=True, verbose_name='Статус')),
                ('score', models.IntegerField(blank=True, default=0, null=True, verbose_name='Баллы')),
                ('correct_count', models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Количество правильных ответов')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='appcourses.Quiz')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quiz_results', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Результат теста',
                'verbose_name_plural': 'Результаты тестов',
            },
        ),
    ]
