# Generated by Django 3.0.3 on 2020-04-22 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0057_quizresult'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_results', to='appcourses.Question'),
        ),
    ]
