# Generated by Django 3.0.3 on 2020-04-23 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0059_question_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questionresult',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
