# Generated by Django 3.0.3 on 2020-04-24 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0060_auto_20200423_1642'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='time_type',
            field=models.CharField(choices=[('a', 'NoneTime'), ('b', 'QuizTime'), ('c', 'QuestionTime')], default='c', max_length=1, null=True, verbose_name='Тип времени'),
        ),
    ]
