# Generated by Django 3.0.3 on 2020-04-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0061_quiz_time_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Время'),
        ),
    ]
