# Generated by Django 3.0.3 on 2020-04-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0062_quiz_duration'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='duration',
            field=models.SmallIntegerField(default=0, null=True, verbose_name='Время в секундах'),
        ),
    ]
