# Generated by Django 3.0.3 on 2020-04-24 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0064_auto_20200424_1051'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizresult',
            name='time_left',
            field=models.SmallIntegerField(blank=True, default=0, null=True, verbose_name='Осталось времени на тест'),
        ),
    ]
