# Generated by Django 3.0.3 on 2020-04-24 12:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0065_quizresult_time_left'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='questionresult',
            options={'verbose_name': 'Ответ пользователя', 'verbose_name_plural': 'Ответы на вопросы тестов'},
        ),
    ]
