# Generated by Django 3.0.3 on 2020-04-26 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0067_auto_20200426_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='index_avatar',
            field=models.SmallIntegerField(blank=True, null=True, verbose_name='Номер изображения'),
        ),
        migrations.AlterField(
            model_name='questionresult',
            name='answer_code',
            field=models.TextField(default='', max_length=2000, null=True, verbose_name='Код ответа пользователя'),
        ),
    ]
