# Generated by Django 3.0.3 on 2020-04-28 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0070_remove_lessonquiz_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contents', to='appcourses.Quiz'),
        ),
    ]
