# Generated by Django 3.0.3 on 2020-04-28 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0071_content_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='quiz',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quizzes', to='appcourses.Quiz'),
        ),
    ]
