# Generated by Django 3.0.3 on 2020-04-30 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0073_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='module',
            name='need_review',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Нужен отзыв'),
        ),
    ]
