# Generated by Django 3.0.3 on 2020-04-30 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0074_module_need_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='estimate',
            field=models.SmallIntegerField(default=0, verbose_name='Оценка'),
        ),
    ]
