# Generated by Django 3.0.3 on 2020-05-01 11:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('appcourses', '0075_review_estimate'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={'model__in': ('module', 'course')}, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
        migrations.AddField(
            model_name='review',
            name='object_id',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
