# Generated by Django 3.0.3 on 2020-05-01 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0076_auto_20200501_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='review',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='review',
            name='object_id',
        ),
    ]
