# Generated by Django 3.0.3 on 2020-05-01 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0077_auto_20200501_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='active',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='Активен'),
        ),
        migrations.AddField(
            model_name='review',
            name='category',
            field=models.CharField(choices=[('e', 'Explicit'), ('f', 'Need fix'), ('c', 'Complement')], max_length=1, null=True, verbose_name='Категория отзыва'),
        ),
    ]
