# Generated by Django 3.0.3 on 2020-05-02 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0078_auto_20200501_1454'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(default='', max_length=2000, verbose_name='Полное описание'),
        ),
        migrations.AlterField(
            model_name='review',
            name='created',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
