# Generated by Django 3.0.3 on 2020-05-04 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0081_currentlesson_course'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='quiz',
            options={'verbose_name': 'Тест', 'verbose_name_plural': 'Тесты'},
        ),
    ]
