# Generated by Django 3.0.3 on 2020-04-15 10:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appcourses', '0046_auto_20200414_2158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CoursePermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('n', 'Редактирование не опубликованных'), ('a', 'Редактирование опубликованных'), ('p', 'Публикация объектов'), ('r', 'Снятие с публикации')], default='n', max_length=1, verbose_name='Тип доступа')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='appcourses.Course')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешение на курс',
                'verbose_name_plural': 'Разрешения на курсы',
            },
        ),
    ]
