# Generated by Django 3.0.3 on 2020-04-15 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apppermission', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('n', 'Редактирование не опубликованных'), ('a', 'Редактирование опубликованных'), ('p', 'Публикация объектов'), ('r', 'Снятие с публикации')], default='n', max_length=1, unique=True, verbose_name='Тип доступа')),
            ],
            options={
                'verbose_name': 'Вид доступа',
                'verbose_name_plural': 'Виды доступа',
            },
        ),
        migrations.RemoveField(
            model_name='coursepermission',
            name='type',
        ),
        migrations.AddField(
            model_name='coursepermission',
            name='access_type',
            field=models.ManyToManyField(to='apppermission.AccessType', verbose_name='Тип доступа'),
        ),
    ]
