# Generated by Django 3.0.3 on 2020-04-15 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apppermission', '0002_auto_20200415_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='accesstype',
            options={'verbose_name': 'Типы доступа', 'verbose_name_plural': 'Тип доступа'},
        ),
    ]
