# Generated by Django 3.0.3 on 2020-04-15 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0046_auto_20200414_2158'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apppermission', '0003_auto_20200415_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.ManyToManyField(to='apppermission.AccessType', verbose_name='Тип доступа')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='appcourses.Lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lesson_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешение на урок',
                'verbose_name_plural': 'Разрешения на уроки',
            },
        ),
    ]
