# Generated by Django 3.0.3 on 2020-04-20 11:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appcourses', '0049_auto_20200420_1303'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apppermission', '0005_modulepermission'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_type', models.ManyToManyField(to='apppermission.AccessType', verbose_name='Тип доступа')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='appcourses.Quiz')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='quiz_permissions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Разрешение на тест',
                'verbose_name_plural': 'Разрешения на тесты',
            },
        ),
    ]
