# Generated by Django 3.0.2 on 2020-01-13 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0003_orderforcheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'В работе'), ('for_check', 'На проверке'), ('done', 'Done')], default='inprogress', max_length=50),
        ),
        migrations.DeleteModel(
            name='OrderForCheck',
        ),
    ]
