# Generated by Django 3.0.2 on 2020-01-14 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0004_auto_20200113_1101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'В работе'), ('done', 'Выполнена'), ('for_check', 'На проверке')], default='inprogress', max_length=50),
        ),
    ]
