# Generated by Django 3.0.2 on 2020-01-16 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0005_auto_20200114_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'В работе'), ('done', 'Выполнена'), ('for_check', 'На проверке'), ('disabled', 'Не активна')], default='inprogress', max_length=50),
        ),
    ]
