# Generated by Django 3.0.2 on 2020-01-17 11:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0015_auto_20200114_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apporders', '0007_orderincheck'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderincheck',
            name='status',
            field=models.CharField(choices=[('incheck', 'Взят на проверку'), ('done', 'Проверен')], default='incheck', max_length=50),
        ),
        migrations.CreateModel(
            name='CheckPointOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rate', models.IntegerField(default=0)),
                ('check_point', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apptasks.CheckPoint')),
                ('order_in_check', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apporders.OrderInCheck')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('user_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apporders.Order')),
            ],
            options={
                'verbose_name': 'Проверенный чекпоит',
                'verbose_name_plural': 'Проверенные чекпоиты',
                'ordering': ('-created',),
            },
        ),
    ]
