# Generated by Django 3.0.2 on 2020-01-17 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0009_checkpointorderitem_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
