# Generated by Django 3.0.2 on 2020-01-17 14:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apptasks', '0015_auto_20200114_1407'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('apporders', '0010_auto_20200117_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='check_point',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apptasks.CheckPoint'),
        ),
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='order_in_check',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apporders.OrderInCheck'),
        ),
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='rate',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='user_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='apporders.Order'),
        ),
    ]
