# Generated by Django 3.0.2 on 2020-01-22 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0011_auto_20200117_1702'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment',
            field=models.TextField(default='', null=True, verbose_name='Комментарий'),
        ),
    ]
