# Generated by Django 3.0.2 on 2020-01-25 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0013_order_repo_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'В работе'), ('done', 'Выполнена'), ('for_check', 'Выполнена'), ('disabled', 'Не активна')], default='inprogress', max_length=50),
        ),
    ]
