# Generated by Django 3.0.2 on 2020-01-30 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0014_auto_20200125_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderincheck',
            name='comment',
            field=models.TextField(default='', null=True, verbose_name='Комментарий'),
        ),
    ]
