# Generated by Django 3.0.2 on 2020-02-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0016_auto_20200208_1814'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cloud_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='github_pages_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='github_repo_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='heroku_url',
        ),
        migrations.RemoveField(
            model_name='order',
            name='repo_url',
        ),
        migrations.AddField(
            model_name='order',
            name='build_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на решение'),
        ),
        migrations.AddField(
            model_name='order',
            name='code_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на исходниик'),
        ),
    ]
