# Generated by Django 3.0.2 on 2020-02-13 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0017_auto_20200208_1817'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='code_url',
            field=models.URLField(null=True, verbose_name='Ссылка на исходниик'),
        ),
    ]
