# Generated by Django 3.0.2 on 2020-02-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0019_auto_20200215_0752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='build_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на решение'),
        ),
        migrations.AlterField(
            model_name='order',
            name='code_url',
            field=models.URLField(blank=True, default='', null=True, verbose_name='Ссылка на исходниик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=2000, null=True, verbose_name='Комментарий'),
        ),
    ]
