# Generated by Django 3.0.2 on 2020-02-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0020_auto_20200216_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Название')),
                ('description', models.TextField(verbose_name='Описание')),
                ('status', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='orderincheck',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=1000, null=True, verbose_name='Комментарий'),
        ),
    ]
