# Generated by Django 3.0.2 on 2020-02-18 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0021_auto_20200217_1456'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Item',
        ),
    ]
