# Generated by Django 3.0.2 on 2020-02-19 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0023_auto_20200218_1430'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkpointorderitem',
            name='user',
        ),
        migrations.RemoveField(
            model_name='checkpointorderitem',
            name='user_order',
        ),
    ]
