# Generated by Django 3.0.2 on 2020-02-19 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0024_auto_20200219_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderincheck',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_order_in_check', to='apporders.Order'),
        ),
    ]
