# Generated by Django 3.0.2 on 2020-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0025_auto_20200219_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkpointorderitem',
            name='comment',
            field=models.TextField(default='', max_length=1000, null=True, verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='orderincheck',
            name='comment',
            field=models.TextField(blank=True, default='', max_length=1500, null=True, verbose_name='Комментарий'),
        ),
    ]
