# Generated by Django 3.0.3 on 2020-03-01 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0028_auto_20200223_1610'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='comment_HTML',
            field=models.TextField(default='', verbose_name='Форматированный комментарий'),
        ),
    ]
