# Generated by Django 3.0.3 on 2020-03-23 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apporders', '0030_auto_20200301_1712'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('inprogress', 'in progress'), ('done', 'done'), ('for_check', 'on check'), ('disabled', 'disabled')], default='inprogress', max_length=50),
        ),
        migrations.AlterField(
            model_name='orderincheck',
            name='status',
            field=models.CharField(choices=[('incheck', 'in check'), ('done', 'done')], default='incheck', max_length=50),
        ),
    ]
