# Generated by Django 3.0.2 on 2020-01-09 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='appaccounts/images/profiles/', verbose_name='Аватар'),
        ),
    ]
