# Generated by Django 3.0.2 on 2020-02-20 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0004_auto_20200215_1644'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='description',
            field=models.TextField(blank=True, max_length=1000, null=True, verbose_name='О себе'),
        ),
    ]
