# Generated by Django 3.0.2 on 2020-02-22 09:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0005_auto_20200220_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_confirm',
            field=models.BooleanField(default=False, verbose_name='E-mail подтвержден'),
        ),
    ]
