# Generated by Django 3.0.2 on 2020-02-22 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0006_profile_email_confirm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='email_confirm',
        ),
    ]
