# Generated by Django 3.0.3 on 2020-05-01 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0007_remove_profile_email_confirm'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='score',
            field=models.IntegerField(blank=True, null=True, verbose_name='Баллы'),
        ),
    ]
