# Generated by Django 3.0.3 on 2020-05-03 18:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appaccounts', '0009_profile_index_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='need_password',
            field=models.BooleanField(default=False, null=True, verbose_name='Нужен пароль'),
        ),
    ]
